MARINE_INITIAL_AMOUNT = 2
MARINE_MAX_AMOUNT = 20
MARAUDERS_MAX_AMOUNT = 6
SIEGE_TANK_MAX_AMOUNT = 4
MEDIVAC_MAX_AMOUNT = 2
LIBERATOR_MAX_AMOUNT = 1

SUPPLY_DEPOT_DANGER_DISTANCE = 11

ORBITAL_UPGRADE_CHECK_DELAY = 20
